apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: darkpodcasting
resources:
  - ../../../base/
images:
  - name: server
    newName: registry.christos.id/darkpodcasting/darkpodcasting-server
    newTag: latest
